INSERT INTO CITY (NAME, CAP) VALUES ('Amantea', '87032');
INSERT INTO CITY (NAME, CAP) VALUES ('Roma', '00144');
INSERT INTO CITY (NAME, CAP) VALUES ('jshdi', '12345');

INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES ('Rino', 'Gaetano');
INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES ('Adriano', 'Celentano');
INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES ('Laura', 'Pausini');