DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
ID INT AUTO_INCREMENT  PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
CAP VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
ID INT AUTO_INCREMENT  PRIMARY KEY,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL
);